version: "3.8"

services:
  hrm-demo-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: hrm-demo-db
    ports:
      - "5121:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
