version: "3.8"

services:
  linkedin-recorder-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: linkedin-recorder
    ports:
      - "5120:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
